### PR TITLE
feat(sidecar-containers): Update to latest available versions

### PR DESCRIPTION
**Pull request by isantospardo**
Update to latest available
- https://kubernetes-csi.github.io/docs/node-driver-registrar.html
- https://kubernetes-csi.github.io/docs/external-provisioner.html
- https://kubernetes-csi.github.io/docs/external-attacher.html
- https://kubernetes-csi.github.io/docs/external-resizer.html

### CODE REVIEW

**Comment by alakae** [comment]
@isantospardo Thank you for your contribution! I'll run our test suite on this PR soon, and then I think we can release this.

**Comment by isantospardo** [comment]
@alakae any update on this? ;)

**Comment by alakae** [comment]
For the following side-cars, a new major version is installed: 

csi-provisioner: https://github.com/kubernetes-csi/external-provisioner/blob/v3.2.0/CHANGELOG/CHANGELOG-3.0.md
csi-attacher: https://github.com/kubernetes-csi/external-attacher/blob/release-4.0/CHANGELOG/CHANGELOG-4.0.md#urgent-upgrade-notes

**Comment by alakae** [comment]
From what I see, the new min required Kubernetes version becomes 1.20.

**Comment by davidhalter** [comment]
LGTM, I feel like the `Kubernetes Compatibility` table in the README should also be updated.

**Comment by alakae** [comment]
I will update the README when I publish the release.

**Comment by alakae** [comment]
@isantospardo Released as v3.4.0. I hope it works as expected. Otherwise, please get in touch with us. Thank you for your contribution.

**Pull request merged**
